// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OcelotTemplate.Services.ArticleManagement.EfCore;

#nullable disable

namespace OcelotTemplate.Services.ArticleManagement.Migrations
{
    [DbContext(typeof(ArticleDbContext))]
    [Migration("20230819064345_InitialArticleWithData")]
    partial class InitialArticleWithData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OcelotTemplate.Services.ArticleManagement.EfCore.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Fk_ArticleCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Fk_ArticleCategoryId");

                    b.ToTable("Articles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A description about samsung a32",
                            Fk_ArticleCategoryId = 1,
                            Name = "Sumsung a32 features"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A description about persian carpet",
                            Fk_ArticleCategoryId = 2,
                            Name = "Persian Carpet properties"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A description about logitec keyboards",
                            Fk_ArticleCategoryId = 1,
                            Name = "logitec Keyboards"
                        });
                });

            modelBuilder.Entity("OcelotTemplate.Services.ArticleManagement.EfCore.Entities.ArticleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ArticleCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "In this article just add about digital.",
                            Title = "Digital Articles"
                        },
                        new
                        {
                            Id = 2,
                            Description = "In this article just add about digital.",
                            Title = "Public articles"
                        },
                        new
                        {
                            Id = 3,
                            Description = "In this article just add about Home facilities.",
                            Title = "Home product"
                        });
                });

            modelBuilder.Entity("OcelotTemplate.Services.ArticleManagement.EfCore.Entities.Article", b =>
                {
                    b.HasOne("OcelotTemplate.Services.ArticleManagement.EfCore.Entities.ArticleCategory", "ArticleCategory")
                        .WithMany("Articles")
                        .HasForeignKey("Fk_ArticleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleCategory");
                });

            modelBuilder.Entity("OcelotTemplate.Services.ArticleManagement.EfCore.Entities.ArticleCategory", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
